spring:
  application:
    name: modulith
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
      platform: all
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:mydatabase}
    username: ${POSTGRES_USERNAME:myuser}
    password: ${POSTGRES_PASSWORD:secret}
  threads:
    virtual:
      enabled: true
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin.tracing.endpoint: 'http://${ZIPKIN_HOST:localhost:9411}/api/v2/spans'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1