spring:
  application:
    name: modulith
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
      platform: all
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:mydatabase}
    username: ${POSTGRES_USERNAME:myuser}
    password: ${POSTGRES_PASSWORD:secret}
  threads:
    virtual:
      enabled: true