CREATE TABLE IF NOT EXISTS student
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

INSERT INTO student (name)
VALUES ('Bobby Tables'),
       ('Mocky Springfield'),
       ('Monoque Flux');
